name: Build, test and package

on: push

jobs:
  package:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: dotnet test --nologo
      - name: Package
        run: |
          (cd BadMedicine.Core && dotnet pack -p:PackageVersion=$(fgrep AssemblyInformationalVersion ../SharedAssemblyInfo.cs|cut -d'"' -f2) -o . --include-source --include-symbols --nologo -c Release)
          (cd BadMedicine && dotnet publish --nologo --runtime win-x64 -c Release --self-contained true -o ../win-x64)
          (cd BadMedicine && dotnet publish --nologo --runtime linux-x64 -c Release --self-contained true -o ../linux-x64)
          (cd win-x64 && zip -9r ../badmedicine-cli-win-x64.zip .)
          (tar czf badmedicine-cli-linux-x64.tgz ./linux-x64)
      - name: Nuget push
        if: contains(github.ref,'refs/tags/')
        run: (cd BadMedicine.Core && nuget push HIC.*.nupkg -skipDuplicate -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_KEY }})
      - name: Upload release binaries
        uses: svenstaro/upload-release-action@2.2.1
        if: contains(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: badmedicine-cli-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
