name: Build, test and package

on: push

jobs:
  package:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: dotnet test
      - name: Package
        run: |
          (cd BadMedicine && dotnet publish -r win-x64 -c Release -o Publish)
          (cd BadMedicine && dotnet publish -r linux-x64 -c Release -o Publish)
          (cd BadMedicine.Core && nuget pack BadMedicine.nuspec -Properties Configuration=Release -IncludeReferencedProjects -Symbols -Version $(fgrep AssemblyInformationalVersion ../SharedAssemblyInfo.cs|cut -d'"' -f2))
          dotnet publish --runtime win-x64 -c Release --self-contained true -o win-x64
          dotnet publish --runtime linux-x64 -c Release --self-contained true -o linux-x64
          (cd win-x64 && zip -9r ../badmedicine-cli-win-x64.zip .)
          (cd linux-x64 && zip -9r ../badmedicine-cli-linux-x64.zip .)
      - name: Nuget push
        if: contains(github.ref,'refs/tags/')
        run: (cd BadMedicine.Core && nuget push HIC.*.nupkg -skipDuplicate -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_KEY }})
      - name: Upload release binaries
        if: contains(github.ref,'refs/tags/')
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["badmedicine-cli-win-x64.zip","badmedicine-cli-linux-x64.zip"]'
